/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['header[_ngcontent-%COMP%] {\r\n  background-color: #000;\r\n}\r\nul.navbar-nav[_ngcontent-%COMP%] { \r\n  padding-top: 25px;\r\n}\r\nnav[_ngcontent-%COMP%] {\r\n  position: fixed;\r\n  z-index: 5;\r\n  width: 100%;\r\n}\r\n.bg-inverse[_ngcontent-%COMP%] {\r\n  background-color: #000 !important;\r\n}\r\n\r\n\r\n\r\n.navbar-nav[_ngcontent-%COMP%]   .nav-link.active[_ngcontent-%COMP%] { color: white; }\r\n\r\n.navbar-toggler[_ngcontent-%COMP%] { background-color: #777; top: 14px; }\r\n.navbar-toggler[_ngcontent-%COMP%]:hover { background-color: #f15f43; }\r\n\r\n.navbar-nav[_ngcontent-%COMP%]   .nav-link[_ngcontent-%COMP%] {\r\n  padding-left: 16px;\r\n  padding-right: 16px;\r\n  font-family: fufont;\r\n  letter-spacing: 1.5px;\r\n  font-size: 14pt;\r\n  color: #f15f43;\r\n}\r\n\r\n.navbar-nav[_ngcontent-%COMP%]   .nav-link[_ngcontent-%COMP%]:hover {\r\n  background-color: #333;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL2hlYWRlci9oZWFkZXIuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1NwZWVkZXIvRG9jdW1lbnRzL25neC1mdWNrL3N0cmljdGRldi9wdWJsaWNfd2Vic2l0ZS9zcmMvYnJvd3Nlci92aWV3cy9oZWFkZXIvaGVhZGVyLmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
