/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../src/browser/views/footer/footer';
const styles_HomepageFooter:any[] = ([] as any[]);
export const RenderType_HomepageFooter:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_HomepageFooter,data:{}});
export function View_HomepageFooter_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['	'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),19,'footer',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),16,'div',[['class','footer_priv']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['\n\n			'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),13,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n				'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          7,'ul',[['class','soc_icons']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n					'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),2,'li',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),1,'a',[['href','https://www.facebook.com/strictdevelopment'],
              ['target','_blank']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'i',[['class',
          'fa fa-facebook']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n					'])),(_l()(),i0.ɵted((null as any),
          ['\n					'])),(_l()(),i0.ɵted((null as any),['\n				'])),(_l()(),i0.ɵted((null as any),
          ['\n\n				'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p',[['class',
          'txt_priv']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['Strict Development, Inc. © 2017'])),(_l()(),
          i0.ɵted((null as any),['\n			'])),(_l()(),i0.ɵted((null as any),['\n		'])),
      (_l()(),i0.ɵted((null as any),['\n	']))],(null as any),(null as any));
}
export function View_HomepageFooter_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'homepage-footer',
      ([] as any[]),(null as any),(null as any),(null as any),View_HomepageFooter_0,
      RenderType_HomepageFooter)),i0.ɵdid(49152,(null as any),0,i1.HomepageFooter,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const HomepageFooterNgFactory:i0.ComponentFactory<i1.HomepageFooter> = i0.ɵccf('homepage-footer',
    i1.HomepageFooter,View_HomepageFooter_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL2Zvb3Rlci9mb290ZXIubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL2Zvb3Rlci9mb290ZXIudHMiLCJuZzovLy9DOi9Vc2Vycy9TcGVlZGVyL0RvY3VtZW50cy9uZ3gtZnVjay9zdHJpY3RkZXYvcHVibGljX3dlYnNpdGUvc3JjL2Jyb3dzZXIvdmlld3MvZm9vdGVyL2Zvb3Rlci5odG1sIiwibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL2Zvb3Rlci9mb290ZXIudHMuSG9tZXBhZ2VGb290ZXJfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcdDxmb290ZXI+XHJcblx0XHQ8ZGl2IGNsYXNzPVwiZm9vdGVyX3ByaXZcIj5cclxuXHJcblx0XHRcdDxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cclxuXHRcdFx0XHQ8dWwgY2xhc3M9XCJzb2NfaWNvbnNcIj5cclxuXHRcdFx0XHRcdDxsaT48YSBocmVmPVwiaHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL3N0cmljdGRldmVsb3BtZW50XCIgdGFyZ2V0PVwiX2JsYW5rXCI+PGkgY2xhc3M9XCJmYSBmYS1mYWNlYm9va1wiPjwvaT48L2E+PC9saT5cclxuXHRcdFx0XHRcdDwhLS0gPGxpPjxhIGhyZWY9XCIjXCI+PGkgY2xhc3M9XCJmYSBmYS10d2l0dGVyXCI+PC9pPjwvYT48L2xpPiAtLT5cclxuXHRcdFx0XHRcdDwhLS0gPGxpPjxhIGhyZWY9XCIjXCI+PGkgY2xhc3M9XCJmYSBmYS1nb29nbGUtcGx1c1wiPjwvaT48L2E+PC9saT4gLS0+XHJcblx0XHRcdFx0PC91bD5cclxuXHJcblx0XHRcdFx0PHAgY2xhc3M9XCJ0eHRfcHJpdlwiPlN0cmljdCBEZXZlbG9wbWVudCwgSW5jLiAmY29weTsgMjAxNzwvcD5cclxuXHRcdFx0PC9kaXY+XHJcblx0XHQ8L2Rpdj5cclxuXHQ8L2Zvb3Rlcj4iLCI8aG9tZXBhZ2UtZm9vdGVyPjwvaG9tZXBhZ2UtZm9vdGVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLHNDQUFDO01BQUE7TUFBQSw4QkFBUSx5Q0FDUDthQUFBO1VBQUEsMERBQXlCO01BQUEsY0FFeEI7TUFBQTtNQUF1QiwyQ0FDdEI7VUFBQTtVQUFBLDhCQUFzQjtNQUNyQjtVQUFBLDBEQUFJO1VBQUE7Y0FBQTtVQUFBLGdCQUFxRTtVQUFBO1VBQUEsZ0JBQXVDLDRDQUNqRDtVQUFBLGNBQ0ksMkNBQy9EO1VBQUEsZUFFTDtVQUFBO01BQW9CLG9FQUF3QztpQkFBQSwyQkFDdkQ7TUFDRDs7O29CQ1pSO01BQUE7K0JBQUEsVUFBQTtNQUFBOzs7In0=
