/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './login-module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/forms';
import * as i4 from '../providers/login-service';
import * as i5 from '../../config/config.app';
import * as i6 from '../../madame/madame-service';
import * as i7 from 'angular2-jwt/angular2-jwt';
import * as i8 from '../../config/profile.app';
import * as i9 from '../providers/auth-guard';
import * as i10 from '../../madame/madame-socket';
import * as i11 from '@angular/http';
import * as i12 from '../../ng2-modal/index';
import * as i13 from '../../madame/index';
import * as i14 from '../providers/index';
export const LoginModuleNgFactory:i0.NgModuleFactory<i1.LoginModule> = i0.ɵcmf(i1.LoginModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.ɵi,
          i3.ɵi,([] as any[])),i0.ɵmpd(4608,i4.LoginService,i4.LoginService,[i5.ConfigApp,
          i6.MadameService]),i0.ɵmpd(4608,i7.JwtHelper,i7.JwtHelper,([] as any[])),
          i0.ɵmpd(135680,i4.LoginCmd,i4.LoginCmd,[i8.ProfileApp,i7.JwtHelper]),i0.ɵmpd(4608,
              i9.AuthGuard,i9.AuthGuard,([] as any[])),i0.ɵmpd(4608,i10.MadameSocket,
              i10.MadameSocket,[i11.Http,i7.AuthHttp]),i0.ɵmpd(512,i2.CommonModule,
              i2.CommonModule,([] as any[])),i0.ɵmpd(512,i3.ɵba,i3.ɵba,([] as any[])),
          i0.ɵmpd(512,i3.FormsModule,i3.FormsModule,([] as any[])),i0.ɵmpd(512,i12.ModalModule,
              i12.ModalModule,([] as any[])),i0.ɵmpd(1024,i7.AuthHttp,i13.authHttpServiceFactory,
              [i11.Http,i11.RequestOptions]),i0.ɵmpd(512,i6.MadameService,i6.MadameService,
              [i11.Http,i7.AuthHttp]),i0.ɵmpd(512,i14.LoginProvidersModule,i14.LoginProvidersModule,
              [i5.ConfigApp,i6.MadameService]),i0.ɵmpd(512,i13.MadameModule,i13.MadameModule,
              ([] as any[])),i0.ɵmpd(512,i1.LoginModule,i1.LoginModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svX3NoYXJlZC9sb2dpbi9icm93c2VyL2xvZ2luLW1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9TcGVlZGVyL0RvY3VtZW50cy9uZ3gtZnVjay9fc2hhcmVkL2xvZ2luL2Jyb3dzZXIvbG9naW4tbW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
