/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './index';
import * as i2 from '@angular/common';
import * as i3 from '../../config/config.app';
import * as i4 from '../../madame/madame-service';
export const LoginProvidersModuleNgFactory:i0.NgModuleFactory<i1.LoginProvidersModule> = i0.ɵcmf(i1.LoginProvidersModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.LoginProvidersModule,i1.LoginProvidersModule,
          [i3.ConfigApp,i4.MadameService])]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svX3NoYXJlZC9sb2dpbi9wcm92aWRlcnMvaW5kZXgubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svX3NoYXJlZC9sb2dpbi9wcm92aWRlcnMvaW5kZXgudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
