/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../homepage-layout/homepage-layout.ngfactory';
import * as i2 from '../../../../../src/browser/views/homepage-layout/homepage-layout';
import * as i3 from '../../../shared/people/people.ngfactory';
import * as i4 from '../../../../../src/shared/people/people';
import * as i5 from '../../../../../src/browser/views/people/people';
const styles_PeopleComponent:any[] = ([] as any[]);
export const RenderType_PeopleComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_PeopleComponent,data:{}});
export function View_PeopleComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),5,'homepage-layout',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_HomepageLayout_0,
      i1.RenderType_HomepageLayout)),i0.ɵdid(49152,(null as any),0,i2.HomepageLayout,
      ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted(0,['\n  '])),(_l()(),
      i0.ɵeld(0,(null as any),0,1,'people-shared-component',([] as any[]),(null as any),
          (null as any),(null as any),i3.View_PeopleSharedComponent_0,i3.RenderType_PeopleSharedComponent)),
      i0.ɵdid(49152,(null as any),0,i4.PeopleSharedComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted(0,['\n'])),(_l()(),i0.ɵted((null as any),
          ['\n']))],(null as any),(null as any));
}
export function View_PeopleComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'people-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_PeopleComponent_0,
      RenderType_PeopleComponent)),i0.ɵdid(49152,(null as any),0,i5.PeopleComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const PeopleComponentNgFactory:i0.ComponentFactory<i5.PeopleComponent> = i0.ɵccf('people-component',
    i5.PeopleComponent,View_PeopleComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL3Blb3BsZS9wZW9wbGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL3Blb3BsZS9wZW9wbGUudHMiLCJuZzovLy9DOi9Vc2Vycy9TcGVlZGVyL0RvY3VtZW50cy9uZ3gtZnVjay9zdHJpY3RkZXYvcHVibGljX3dlYnNpdGUvc3JjL2Jyb3dzZXIvdmlld3MvcGVvcGxlL3Blb3BsZS5odG1sIiwibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL3Blb3BsZS9wZW9wbGUudHMuUGVvcGxlQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGhvbWVwYWdlLWxheW91dD5cclxuICA8cGVvcGxlLXNoYXJlZC1jb21wb25lbnQ+PC9wZW9wbGUtc2hhcmVkLWNvbXBvbmVudD5cclxuPC9ob21lcGFnZS1sYXlvdXQ+XHJcbiIsIjxwZW9wbGUtY29tcG9uZW50PjwvcGVvcGxlLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtrQ0FBQSxVQUFBO01BQUEsMkNBQWlCLDZCQUNmO2FBQUE7VUFBQTthQUFBO1VBQUEsZUFBbUQsMkJBQ25DO1VBQUE7OztvQkNGbEI7TUFBQTtnQ0FBQSxVQUFBO01BQUE7OzsifQ==
