/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../homepage-layout/homepage-layout.ngfactory';
import * as i2 from '../../../../../src/browser/views/homepage-layout/homepage-layout';
import * as i3 from '../../../shared/people/people.ngfactory';
import * as i4 from '../../../../../src/shared/people/people';
import * as i5 from '@angular/router';
import * as i6 from '@angular/common';
import * as i7 from '../../../../../src/browser/views/people/people';
const styles_PeopleComponent:any[] = ([] as any[]);
export const RenderType_PeopleComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_PeopleComponent,data:{}});
export function View_PeopleComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),13,'homepage-layout',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_HomepageLayout_0,
      i1.RenderType_HomepageLayout)),i0.ɵdid(49152,(null as any),0,i2.HomepageLayout,
      ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted(0,['\n  '])),(_l()(),
      i0.ɵeld(0,(null as any),0,1,'people-shared-component',([] as any[]),(null as any),
          (null as any),(null as any),i3.View_PeopleSharedComponent_0,i3.RenderType_PeopleSharedComponent)),
      i0.ɵdid(49152,(null as any),0,i4.PeopleSharedComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted(0,['\n  '])),(_l()(),i0.ɵeld(0,(null as any),
          0,0,'br',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted(0,['\n  '])),(_l()(),i0.ɵeld(0,(null as any),
          0,4,'p',[['class','txt4']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵeld(0,(null as any),(null as any),3,'a',[['class',
          'call_to_action']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],
          (_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,10).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i5.RouterLinkWithHref,
          [i5.Router,i5.ActivatedRoute,i6.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),i0.ɵpad(1),(_l()(),i0.ɵted((null as any),['Contact Us'])),
      (_l()(),i0.ɵted(0,['\n'])),(_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    const currVal_2:any = _ck(_v,11,0,'/contact');
    _ck(_v,10,0,currVal_2);
  },(_ck,_v) => {
    const currVal_0:any = i0.ɵnov(_v,10).target;
    const currVal_1:any = i0.ɵnov(_v,10).href;
    _ck(_v,9,0,currVal_0,currVal_1);
  });
}
export function View_PeopleComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'people-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_PeopleComponent_0,
      RenderType_PeopleComponent)),i0.ɵdid(49152,(null as any),0,i7.PeopleComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const PeopleComponentNgFactory:i0.ComponentFactory<i7.PeopleComponent> = i0.ɵccf('people-component',
    i7.PeopleComponent,View_PeopleComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL3Blb3BsZS9wZW9wbGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL3Blb3BsZS9wZW9wbGUudHMiLCJuZzovLy9DOi9Vc2Vycy9TcGVlZGVyL0RvY3VtZW50cy9uZ3gtZnVjay9zdHJpY3RkZXYvcHVibGljX3dlYnNpdGUvc3JjL2Jyb3dzZXIvdmlld3MvcGVvcGxlL3Blb3BsZS5odG1sIiwibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL3Blb3BsZS9wZW9wbGUudHMuUGVvcGxlQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGhvbWVwYWdlLWxheW91dD5cclxuICA8cGVvcGxlLXNoYXJlZC1jb21wb25lbnQ+PC9wZW9wbGUtc2hhcmVkLWNvbXBvbmVudD5cclxuICA8YnIgLz5cclxuICA8cCBjbGFzcz1cInR4dDRcIj48YSBjbGFzcz1cImNhbGxfdG9fYWN0aW9uXCIgW3JvdXRlckxpbmtdPVwiWycvY29udGFjdCddXCI+Q29udGFjdCBVczwvYT48L3A+XHJcbjwvaG9tZXBhZ2UtbGF5b3V0PlxyXG4iLCI8cGVvcGxlLWNvbXBvbmVudD48L3Blb3BsZS1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtrQ0FBQSxVQUFBO01BQUEsMkNBQWlCLDZCQUNmO2FBQUE7VUFBQTthQUFBO1VBQUEsZUFBbUQsNkJBQ25EO1VBQUE7VUFBQSxnQkFBTSw2QkFDTjtVQUFBO1VBQUEsZ0JBQWdCO1VBQUE7VUFBQTtZQUFBO1lBQUE7Y0FBQTtrQkFBQTtjQUFBO1lBQUE7WUFBQTtVQUFBLHVDQUFBO1VBQUE7VUFBQSxzQkFBMEIsSUFBNEI7TUFBa0IsMkJBQ3hFO0lBRDBCO0lBQTFCLFlBQTBCLFNBQTFCOztJQUFBO0lBQUE7SUFBQSxXQUFBLG1CQUFBOzs7O29CQ0hsQjtNQUFBO2dDQUFBLFVBQUE7TUFBQTs7OyJ9
