/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../header/header.ngfactory';
import * as i2 from '../../../../../src/browser/views/header/header';
import * as i3 from '../footer/footer.ngfactory';
import * as i4 from '../../../../../src/browser/views/footer/footer';
import * as i5 from '../../../../../src/browser/views/homepage-layout/homepage-layout';
const styles_HomepageLayout:any[] = ([] as any[]);
export const RenderType_HomepageLayout:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_HomepageLayout,data:{}});
export function View_HomepageLayout_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'homepage-header',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_HomepageHeader_0,
      i1.RenderType_HomepageHeader)),i0.ɵdid(245760,(null as any),0,i2.HomepageHeader,
      ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted((null as any),['\n'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',[['class','white_space']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          0,'div',[['class','orange_bar']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['  \n'])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),0,'div',[['class','bubbles']],(null as any),
              (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),6,'div',[['class',
          'img-box txt_cntr']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),3,'div',[['class','desc_bubble row']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n    '])),i0.ɵncd((null as any),0),(_l()(),i0.ɵted((null as any),['\n  '])),
      (_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),['\n\n'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'homepage-footer',([] as any[]),
          (null as any),(null as any),(null as any),i3.View_HomepageFooter_0,i3.RenderType_HomepageFooter)),
      i0.ɵdid(49152,(null as any),0,i4.HomepageFooter,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export function View_HomepageLayout_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'homepage-layout',
      ([] as any[]),(null as any),(null as any),(null as any),View_HomepageLayout_0,
      RenderType_HomepageLayout)),i0.ɵdid(49152,(null as any),0,i5.HomepageLayout,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const HomepageLayoutNgFactory:i0.ComponentFactory<i5.HomepageLayout> = i0.ɵccf('homepage-layout',
    i5.HomepageLayout,View_HomepageLayout_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL2hvbWVwYWdlLWxheW91dC9ob21lcGFnZS1sYXlvdXQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL2hvbWVwYWdlLWxheW91dC9ob21lcGFnZS1sYXlvdXQudHMiLCJuZzovLy9DOi9Vc2Vycy9TcGVlZGVyL0RvY3VtZW50cy9uZ3gtZnVjay9zdHJpY3RkZXYvcHVibGljX3dlYnNpdGUvc3JjL2Jyb3dzZXIvdmlld3MvaG9tZXBhZ2UtbGF5b3V0L2hvbWVwYWdlLWxheW91dC5odG1sIiwibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL2hvbWVwYWdlLWxheW91dC9ob21lcGFnZS1sYXlvdXQudHMuSG9tZXBhZ2VMYXlvdXRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aG9tZXBhZ2UtaGVhZGVyPjwvaG9tZXBhZ2UtaGVhZGVyPlxyXG48ZGl2IGNsYXNzPVwid2hpdGVfc3BhY2VcIj48L2Rpdj5cclxuPGRpdiBjbGFzcz1cIm9yYW5nZV9iYXJcIj48L2Rpdj4gIFxyXG48ZGl2IGNsYXNzPVwiYnViYmxlc1wiPjwvZGl2PlxyXG5cclxuPGRpdiBjbGFzcz1cImltZy1ib3ggdHh0X2NudHJcIj5cclxuICA8ZGl2IGNsYXNzPVwiZGVzY19idWJibGUgcm93XCI+XHJcbiAgICA8bmctY29udGVudD48L25nLWNvbnRlbnQ+XHJcbiAgPC9kaXY+XHJcbjwvZGl2PlxyXG5cclxuPGhvbWVwYWdlLWZvb3Rlcj48L2hvbWVwYWdlLWZvb3Rlcj4iLCI8aG9tZXBhZ2UtbGF5b3V0PjwvaG9tZXBhZ2UtbGF5b3V0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO2tDQUFBLFVBQUE7TUFBQSwyQ0FBbUM7TUFDbkM7VUFBQTtNQUErQix1Q0FDL0I7VUFBQTtVQUFBLDhCQUE4Qix5Q0FDOUI7aUJBQUE7Y0FBQSwwREFBMkI7VUFBQSxXQUUzQjtVQUFBO1VBQUEsZ0JBQThCLHlDQUM1QjtVQUFBO1VBQUEsMERBQTZCO1VBQUEsb0JBQzNCLGtCQUF5QjtNQUNyQix1Q0FDRjtNQUVOO1VBQUE7YUFBQTtVQUFBO0lBWEE7Ozs7b0JDQUE7TUFBQTsrQkFBQSxVQUFBO01BQUE7OzsifQ==
