/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../ng2-modal/Modal.ngfactory';
import * as i2 from '../../../../../../../_shared/ng2-modal/Modal';
import * as i3 from './login.ngfactory';
import * as i4 from '../../../../../../../_shared/login/browser/views/login';
import * as i5 from '../../../../../../../_shared/login/providers/login-service';
import * as i6 from '@angular/router';
import * as i7 from '../../../../../../../_shared/login/browser/views/login-modal';
const styles_LoginModal:any[] = ([] as any[]);
export const RenderType_LoginModal:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_LoginModal,
    data:{}});
export function View_LoginModal_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{ModalLogin:0}),i0.ɵqud(402653184,2,{Login:0}),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),9,'ng-modal',[['style','z-index: 2000;']],
          (null as any),(null as any),(null as any),i1.View_Ng2Modal_0,i1.RenderType_Ng2Modal)),
      i0.ɵdid(180224,[[1,4],['ModalLogin',4]],0,i2.Ng2Modal,([] as any[]),{closeOnEscape:[0,
          'closeOnEscape'],closeOnOutsideClick:[1,'closeOnOutsideClick'],hideCloseButton:[2,
          'hideCloseButton'],showHeader:[3,'showHeader'],showFooter:[4,'showFooter']},
          (null as any)),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,
          (null as any),1,5,'modal-content',([] as any[]),(null as any),(null as any),
          (null as any),i1.View_ModalContent_0,i1.RenderType_ModalContent)),i0.ɵdid(49152,
          (null as any),0,i2.ModalContent,([] as any[]),(null as any),(null as any)),
      (_l()(),i0.ɵted(0,['\n      '])),(_l()(),i0.ɵeld(0,(null as any),0,1,'login-component',
          ([] as any[]),(null as any),(null as any),(null as any),i3.View_LoginComponent_0,
          i3.RenderType_LoginComponent)),i0.ɵdid(114688,[[2,4],['Login',4]],0,i4.LoginComponent,
          [i5.LoginService,i0.Renderer,i6.Router,i6.ActivatedRoute],{isModal:[0,'isModal']},
          (null as any)),(_l()(),i0.ɵted(0,['\n    '])),(_l()(),i0.ɵted((null as any),
          ['\n  ']))],(_ck,_v) => {
    const currVal_0:any = true;
    const currVal_1:any = true;
    const currVal_2:any = false;
    const currVal_3:any = false;
    const currVal_4:any = false;
    _ck(_v,3,0,currVal_0,currVal_1,currVal_2,currVal_3,currVal_4);
    const currVal_5:any = true;
    _ck(_v,9,0,currVal_5);
  },(null as any));
}
export function View_LoginModal_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'login-modal',
      ([] as any[]),(null as any),(null as any),(null as any),View_LoginModal_0,RenderType_LoginModal)),
      i0.ɵdid(4374528,(null as any),0,i7.LoginModal,[i0.ChangeDetectorRef],(null as any),
          (null as any))],(null as any),(null as any));
}
export const LoginModalNgFactory:i0.ComponentFactory<i7.LoginModal> = i0.ɵccf('login-modal',
    i7.LoginModal,View_LoginModal_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svX3NoYXJlZC9sb2dpbi9icm93c2VyL3ZpZXdzL2xvZ2luLW1vZGFsLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1NwZWVkZXIvRG9jdW1lbnRzL25neC1mdWNrL19zaGFyZWQvbG9naW4vYnJvd3Nlci92aWV3cy9sb2dpbi1tb2RhbC50cyIsIm5nOi8vL0M6L1VzZXJzL1NwZWVkZXIvRG9jdW1lbnRzL25neC1mdWNrL19zaGFyZWQvbG9naW4vYnJvd3Nlci92aWV3cy9sb2dpbi1tb2RhbC50cy5Mb2dpbk1vZGFsLmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9TcGVlZGVyL0RvY3VtZW50cy9uZ3gtZnVjay9fc2hhcmVkL2xvZ2luL2Jyb3dzZXIvdmlld3MvbG9naW4tbW9kYWwudHMuTG9naW5Nb2RhbF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxuZy1tb2RhbCBzdHlsZT1cInotaW5kZXg6IDIwMDA7XCIgI01vZGFsTG9naW5cbiAgICAgIFtoaWRlQ2xvc2VCdXR0b25dPVwiZmFsc2VcIlxuICAgICAgW2Nsb3NlT25Fc2NhcGVdPVwidHJ1ZVwiXG4gICAgICBbY2xvc2VPbk91dHNpZGVDbGlja109XCJ0cnVlXCJcbiAgICAgIFtzaG93SGVhZGVyXT1cImZhbHNlXCJcbiAgICAgIFtzaG93Rm9vdGVyXT1cImZhbHNlXCJcbiAgPlxuICAgIDxtb2RhbC1jb250ZW50PlxuICAgICAgPGxvZ2luLWNvbXBvbmVudCAjTG9naW4gW2lzTW9kYWxdPVwidHJ1ZVwiPjwvbG9naW4tY29tcG9uZW50PlxuICAgIDwvbW9kYWwtY29udGVudD5cbiAgPC9uZy1tb2RhbD4iLCI8bG9naW4tbW9kYWw+PC9sb2dpbi1tb2RhbD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNBQTtVQUFBO2FBQUE7VUFBQTtVQUFBO1VBQUEsZUFNRywyQ0FDQztVQUFBO1VBQUEseUVBQUE7VUFBQTtNQUFlLGlDQUNiO1VBQUE7c0NBQUEsVUFBQTtVQUFBO1VBQUEsZUFBMkQsK0JBQzdDO1VBQUE7SUFQZDtJQUNBO0lBRkE7SUFHQTtJQUNBO0lBTE4sV0FFTSxVQUNBLFVBRkEsVUFHQSxVQUNBLFNBTE47SUFROEI7SUFBeEIsV0FBd0IsU0FBeEI7Ozs7b0JDUk47TUFBQTthQUFBO1VBQUE7OzsifQ==
