/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../src/browser/views/page-not-found/page-not-found';
const styles_PageNotFoundComponent:any[] = ([] as any[]);
export const RenderType_PageNotFoundComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_PageNotFoundComponent,data:{}});
export function View_PageNotFoundComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['Page Not Found']))],(null as any),
      (null as any));
}
export function View_PageNotFoundComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'page-not-found-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_PageNotFoundComponent_0,
      RenderType_PageNotFoundComponent)),i0.ɵdid(49152,(null as any),0,i1.PageNotFoundComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const PageNotFoundComponentNgFactory:i0.ComponentFactory<i1.PageNotFoundComponent> = i0.ɵccf('page-not-found-component',
    i1.PageNotFoundComponent,View_PageNotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL3BhZ2Utbm90LWZvdW5kL3BhZ2Utbm90LWZvdW5kLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1NwZWVkZXIvRG9jdW1lbnRzL25neC1mdWNrL3N0cmljdGRldi9wdWJsaWNfd2Vic2l0ZS9zcmMvYnJvd3Nlci92aWV3cy9wYWdlLW5vdC1mb3VuZC9wYWdlLW5vdC1mb3VuZC50cyIsIm5nOi8vL0M6L1VzZXJzL1NwZWVkZXIvRG9jdW1lbnRzL25neC1mdWNrL3N0cmljdGRldi9wdWJsaWNfd2Vic2l0ZS9zcmMvYnJvd3Nlci92aWV3cy9wYWdlLW5vdC1mb3VuZC9wYWdlLW5vdC1mb3VuZC5odG1sIiwibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL3BhZ2Utbm90LWZvdW5kL3BhZ2Utbm90LWZvdW5kLnRzLlBhZ2VOb3RGb3VuZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlBhZ2UgTm90IEZvdW5kIiwiPHBhZ2Utbm90LWZvdW5kLWNvbXBvbmVudD48L3BhZ2Utbm90LWZvdW5kLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTs7OztvQkNBQTtNQUFBO3NDQUFBLFVBQUE7TUFBQTs7OyJ9
