/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../homepage-layout/homepage-layout.ngfactory';
import * as i2 from '../../../../../src/browser/views/homepage-layout/homepage-layout';
import * as i3 from '../../../shared/contact/contact.ngfactory';
import * as i4 from '../../../../../src/shared/contact/contact';
import * as i5 from '../../../../../src/browser/views/contact/contact';
const styles_ContactComponent:any[] = ([] as any[]);
export const RenderType_ContactComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ContactComponent,data:{}});
export function View_ContactComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),5,'homepage-layout',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_HomepageLayout_0,
      i1.RenderType_HomepageLayout)),i0.ɵdid(49152,(null as any),0,i2.HomepageLayout,
      ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted(0,['\n  '])),(_l()(),
      i0.ɵeld(0,(null as any),0,1,'contact-shared-component',([] as any[]),(null as any),
          (null as any),(null as any),i3.View_ContactSharedComponent_0,i3.RenderType_ContactSharedComponent)),
      i0.ɵdid(49152,(null as any),0,i4.ContactSharedComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted(0,['\n'])),(_l()(),i0.ɵted((null as any),
          ['\n']))],(null as any),(null as any));
}
export function View_ContactComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'contact-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_ContactComponent_0,
      RenderType_ContactComponent)),i0.ɵdid(49152,(null as any),0,i5.ContactComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ContactComponentNgFactory:i0.ComponentFactory<i5.ContactComponent> = i0.ɵccf('contact-component',
    i5.ContactComponent,View_ContactComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL2NvbnRhY3QvY29udGFjdC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9TcGVlZGVyL0RvY3VtZW50cy9uZ3gtZnVjay9zdHJpY3RkZXYvcHVibGljX3dlYnNpdGUvc3JjL2Jyb3dzZXIvdmlld3MvY29udGFjdC9jb250YWN0LnRzIiwibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL2NvbnRhY3QvY29udGFjdC5odG1sIiwibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL3ZpZXdzL2NvbnRhY3QvY29udGFjdC50cy5Db250YWN0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGhvbWVwYWdlLWxheW91dD5cclxuICA8Y29udGFjdC1zaGFyZWQtY29tcG9uZW50PjwvY29udGFjdC1zaGFyZWQtY29tcG9uZW50PlxyXG48L2hvbWVwYWdlLWxheW91dD5cclxuIiwiPGNvbnRhY3QtY29tcG9uZW50PjwvY29udGFjdC1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7a0NBQUEsVUFBQTtNQUFBLDJDQUFpQiw2QkFDZjthQUFBO1VBQUE7YUFBQTtVQUFBLGVBQXFELDJCQUNyQztVQUFBOzs7b0JDRmxCO01BQUE7aUNBQUEsVUFBQTtNQUFBOzs7In0=
