/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/shared/homepage-header/homepage-header';
const styles_HomepageHeaderComponent:any[] = ([] as any[]);
export const RenderType_HomepageHeaderComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_HomepageHeaderComponent,data:{}});
export function View_HomepageHeaderComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),6,'div',[['class',
      'strictd_logo_box']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'a',[['class','strictd_circle']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),[' '])),
      (_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          0,'img',[['alt','Strict Development, Inc.'],['class','strictd_logo'],['src',
              'img/logo.png']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',[['class',
          'navbar-brand']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['STRICT DEVELOPMENT, INC.'])),
      (_l()(),i0.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_HomepageHeaderComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'homepage-header-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_HomepageHeaderComponent_0,
      RenderType_HomepageHeaderComponent)),i0.ɵdid(49152,(null as any),0,i1.HomepageHeaderComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const HomepageHeaderComponentNgFactory:i0.ComponentFactory<i1.HomepageHeaderComponent> = i0.ɵccf('homepage-header-component',
    i1.HomepageHeaderComponent,View_HomepageHeaderComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9zaGFyZWQvaG9tZXBhZ2UtaGVhZGVyL2hvbWVwYWdlLWhlYWRlci5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9TcGVlZGVyL0RvY3VtZW50cy9uZ3gtZnVjay9zdHJpY3RkZXYvcHVibGljX3dlYnNpdGUvc3JjL3NoYXJlZC9ob21lcGFnZS1oZWFkZXIvaG9tZXBhZ2UtaGVhZGVyLnRzIiwibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9zaGFyZWQvaG9tZXBhZ2UtaGVhZGVyL2hvbWVwYWdlLWhlYWRlci5odG1sIiwibmc6Ly8vQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9zaGFyZWQvaG9tZXBhZ2UtaGVhZGVyL2hvbWVwYWdlLWhlYWRlci50cy5Ib21lcGFnZUhlYWRlckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJzdHJpY3RkX2xvZ29fYm94XCI+XHJcbiAgPGEgY2xhc3M9XCJzdHJpY3RkX2NpcmNsZVwiPiZuYnNwOzwvYT5cclxuICA8aW1nIGNsYXNzPVwic3RyaWN0ZF9sb2dvXCIgc3JjPVwiaW1nL2xvZ28ucG5nXCIgYWx0PVwiU3RyaWN0IERldmVsb3BtZW50LCBJbmMuXCI+XHJcbjwvZGl2PlxyXG48ZGl2IGNsYXNzPVwibmF2YmFyLWJyYW5kXCI+U1RSSUNUIERFVkVMT1BNRU5ULCBJTkMuPC9kaXY+XHJcbiIsIjxob21lcGFnZS1oZWFkZXItY29tcG9uZW50PjwvaG9tZXBhZ2UtaGVhZGVyLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQUEsZ0JBQThCLHlDQUM1QjtNQUFBO01BQUEsNENBQTBCO01BQVUseUNBQ3BDO1VBQUE7Y0FBQTtVQUFBLGdCQUE0RSx1Q0FDeEU7VUFBQSxTQUNOO1VBQUE7VUFBQSxnQkFBMEI7TUFBOEI7OztvQkNKeEQ7TUFBQTt3Q0FBQSxVQUFBO01BQUE7OzsifQ==
