/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/browser/app/app-module';
import * as i2 from '../../../../src/browser/app/app.component';
import * as i3 from '../views/homepage/homepage.ngfactory';
import * as i4 from '../views/code/code.ngfactory';
import * as i5 from '../views/people/people.ngfactory';
import * as i6 from '../views/contact/contact.ngfactory';
import * as i7 from '../views/page-not-found/page-not-found.ngfactory';
import * as i8 from './app.component.ngfactory';
import * as i9 from '@angular/common';
import * as i10 from '@angular/platform-browser';
import * as i11 from '@angular/forms';
import * as i12 from '../../../../../../_shared/login/providers/login-service';
import * as i13 from '../../../../../../_shared/config/config.app';
import * as i14 from '../../../../../../_shared/madame/madame-service';
import * as i15 from 'angular2-jwt/angular2-jwt';
import * as i16 from '../../../../../../_shared/config/profile.app';
import * as i17 from '../../../../../../_shared/login/providers/auth-guard';
import * as i18 from '../../../../../../_shared/madame/madame-socket';
import * as i19 from '@angular/http';
import * as i20 from '@angular/router';
import * as i21 from '../../../../../../_shared/config/permissions.app';
import * as i22 from '@ngx-meta/core/src/meta.loader';
import * as i23 from '@ngx-meta/core/index';
import * as i24 from '@ngx-meta/core/src/meta.service';
import * as i25 from '@ngx-meta/core/src/meta.guard';
import * as i26 from 'class-transformer/ClassTransformer';
import * as i27 from '../../../../src/browser/views/homepage/homepage';
import * as i28 from '../../../../src/browser/views/code/code';
import * as i29 from '../../../../src/browser/views/people/people';
import * as i30 from '../../../../src/browser/views/contact/contact';
import * as i31 from '../../../../src/browser/views/page-not-found/page-not-found';
import * as i32 from '../../../../../../_shared/config/config-providers-module';
import * as i33 from '../../../../../../_shared/ng2-modal/index';
import * as i34 from '../../../../../../_shared/madame/index';
import * as i35 from '../../../../../../_shared/login/providers/index';
import * as i36 from '../../../../../../_shared/login/browser/login-module';
import * as i37 from '../../../../src/shared/website-shared-module';
import * as i38 from '../../../../src/browser/website-module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.App],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.HomepageComponentNgFactory,i4.CodeComponentNgFactory,i5.PeopleComponentNgFactory,
              i6.ContactComponentNgFactory,i7.PageNotFoundComponentNgFactory,i8.AppNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i9.NgLocalization,i9.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i10.DomSanitizer,i10.ɵe,[i9.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i10.DomSanitizer]),i0.ɵmpd(4608,
              i10.HAMMER_GESTURE_CONFIG,i10.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i10.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i10.ɵDomEventsPlugin(p0_0),new i10.ɵKeyEventsPlugin(p1_0),
                    new i10.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i9.DOCUMENT,i9.DOCUMENT,i9.DOCUMENT,i10.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i10.EventManager,i10.EventManager,[i10.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i10.ɵDomSharedStylesHost,i10.ɵDomSharedStylesHost,[i9.DOCUMENT]),
          i0.ɵmpd(4608,i10.ɵDomRendererFactory2,i10.ɵDomRendererFactory2,[i10.EventManager,
              i10.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i10.ɵDomRendererFactory2]),i0.ɵmpd(6144,i10.ɵSharedStylesHost,(null as any),
              [i10.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i10.Meta,i10.Meta,[i9.DOCUMENT]),i0.ɵmpd(4608,
              i10.Title,i10.Title,[i9.DOCUMENT]),i0.ɵmpd(4608,i11.ɵi,i11.ɵi,([] as any[])),
          i0.ɵmpd(4608,i12.LoginService,i12.LoginService,[i13.ConfigApp,i14.MadameService]),
          i0.ɵmpd(4608,i15.JwtHelper,i15.JwtHelper,([] as any[])),i0.ɵmpd(135680,i16.ProfileApp,
              i16.ProfileApp,[i15.JwtHelper]),i0.ɵmpd(135680,i12.LoginCmd,i12.LoginCmd,
              [i16.ProfileApp,i15.JwtHelper]),i0.ɵmpd(4608,i17.AuthGuard,i17.AuthGuard,
              ([] as any[])),i0.ɵmpd(4608,i18.MadameSocket,i18.MadameSocket,[i19.Http,
              i15.AuthHttp]),i0.ɵmpd(5120,i20.ActivatedRoute,i20.ɵf,[i20.Router]),
          i0.ɵmpd(4608,i20.NoPreloading,i20.NoPreloading,([] as any[])),i0.ɵmpd(6144,
              i20.PreloadingStrategy,(null as any),[i20.NoPreloading]),i0.ɵmpd(135680,
              i20.RouterPreloader,i20.RouterPreloader,[i20.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i20.PreloadingStrategy]),i0.ɵmpd(4608,i20.PreloadAllModules,
              i20.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i20.ROUTER_INITIALIZER,
              i20.ɵi,[i20.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i20.ROUTER_INITIALIZER]),i0.ɵmpd(135680,i21.PermissionsApp,i21.PermissionsApp,
              ([] as any[])),i0.ɵmpd(5120,i22.MetaLoader,i23.metaFactory,([] as any[])),
          i0.ɵmpd(4608,i24.MetaService,i24.MetaService,[i22.MetaLoader,i10.Title,i10.Meta]),
          i0.ɵmpd(4608,i25.MetaGuard,i25.MetaGuard,[i24.MetaService]),i0.ɵmpd(4608,
              i26.ClassTransformer,i26.ClassTransformer,([] as any[])),i0.ɵmpd(512,
              i9.CommonModule,i9.CommonModule,([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,
              i10.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,() => {
            return [i20.ɵb()];
          },([] as any[])),i0.ɵmpd(512,i20.ɵg,i20.ɵg,[i0.Injector]),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any,p1_0:any) => {
                return [i10.ɵc(p0_0,p0_1),i20.ɵh(p1_0)];
              },[[2,i10.NgProbeToken],[2,i0.NgProbeToken],i20.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i10.BrowserModule,i10.BrowserModule,[[3,i10.BrowserModule]]),
          i0.ɵmpd(512,i19.HttpModule,i19.HttpModule,([] as any[])),i0.ɵmpd(512,i11.ɵba,
              i11.ɵba,([] as any[])),i0.ɵmpd(512,i11.FormsModule,i11.FormsModule,([] as any[])),
          i0.ɵmpd(1024,i20.ɵa,i20.ɵd,[[3,i20.Router]]),i0.ɵmpd(512,i20.UrlSerializer,
              i20.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i20.ChildrenOutletContexts,
              i20.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i20.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i9.LocationStrategy,i20.ɵc,[i9.PlatformLocation,
              [2,i9.APP_BASE_HREF],i20.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i9.Location,
              i9.Location,[i9.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i20.ROUTES,
              () => {
                return [[{path:'',component:i27.HomepageComponent,canActivate:[i25.MetaGuard],
                    data:{meta:{title:'Strict Development, Inc',description:'Custom App using Angular'}}},
                    {path:'code',component:i28.CodeComponent,canActivate:[i25.MetaGuard],
                        data:{meta:{title:'Code | Strict Development, Inc',description:'Custom Apps using Angular'}}},
                    {path:'people',component:i29.PeopleComponent,canActivate:[i25.MetaGuard],
                        data:{meta:{title:'People | Strict Development, Inc',description:'People of Strict Development'}}},
                    {path:'contact',component:i30.ContactComponent,canActivate:[i25.MetaGuard],
                        data:{meta:{title:'Contact | Strict Development, Inc',description:'Get A hold of us'}}},
                    {path:'registration',loadChildren:'../../../../registration/src/browser/registration-routing#RegistrationRouting'},
                    {path:'',redirectTo:'/home',pathMatch:'full'},{path:'**',component:i31.PageNotFoundComponent}]];
              },([] as any[])),i0.ɵmpd(1024,i20.Router,i20.ɵe,[i0.ApplicationRef,i20.UrlSerializer,
              i20.ChildrenOutletContexts,i9.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i20.ROUTES,i20.ROUTER_CONFIGURATION,[2,i20.UrlHandlingStrategy],
              [2,i20.RouteReuseStrategy]]),i0.ɵmpd(512,i20.RouterModule,i20.RouterModule,
              [[2,i20.ɵa],[2,i20.Router]]),i0.ɵmpd(512,i32.ConfigProvidersModule,i32.ConfigProvidersModule,
              ([] as any[])),i0.ɵmpd(512,i33.ModalModule,i33.ModalModule,([] as any[])),
          i0.ɵmpd(131584,i13.ConfigApp,i13.ConfigApp,([] as any[])),i0.ɵmpd(512,i19.BrowserXhr,
              i19.BrowserXhr,([] as any[])),i0.ɵmpd(512,i19.ResponseOptions,i19.BaseResponseOptions,
              ([] as any[])),i0.ɵmpd(1024,i19.XSRFStrategy,i19.ɵb,([] as any[])),i0.ɵmpd(512,
              i19.XHRBackend,i19.XHRBackend,[i19.BrowserXhr,i19.ResponseOptions,i19.XSRFStrategy]),
          i0.ɵmpd(512,i19.RequestOptions,i19.BaseRequestOptions,([] as any[])),i0.ɵmpd(1024,
              i19.Http,i19.ɵc,[i19.XHRBackend,i19.RequestOptions]),i0.ɵmpd(1024,i15.AuthHttp,
              i34.authHttpServiceFactory,[i19.Http,i19.RequestOptions]),i0.ɵmpd(512,
              i14.MadameService,i14.MadameService,[i19.Http,i15.AuthHttp]),i0.ɵmpd(512,
              i35.LoginProvidersModule,i35.LoginProvidersModule,[i13.ConfigApp,i14.MadameService]),
          i0.ɵmpd(512,i34.MadameModule,i34.MadameModule,([] as any[])),i0.ɵmpd(512,
              i36.LoginModule,i36.LoginModule,([] as any[])),i0.ɵmpd(512,i23.MetaModule,
              i23.MetaModule,[[3,i23.MetaModule]]),i0.ɵmpd(512,i37.WebsiteSharedModule,
              i37.WebsiteSharedModule,([] as any[])),i0.ɵmpd(512,i38.WebsiteModule,
              i38.WebsiteModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,
              [i0.ApplicationRef])]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL2FwcC9hcHAtbW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1NwZWVkZXIvRG9jdW1lbnRzL25neC1mdWNrL3N0cmljdGRldi9wdWJsaWNfd2Vic2l0ZS9zcmMvYnJvd3Nlci9hcHAvYXBwLW1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
