/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../styles/app.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../_shared/login/browser/views/login-modal.ngfactory';
import * as i3 from '../../../../../../_shared/login/browser/views/login-modal';
import * as i4 from '@angular/router';
import * as i5 from '../../../../src/browser/app/app.component';
import * as i6 from '../../../../../../_shared/config/config.app';
import * as i7 from '@ngx-meta/core/src/meta.service';
import * as i8 from '../../../../../../_shared/config/profile.app';
import * as i9 from '../../../../../../_shared/config/permissions.app';
import * as i10 from '../../../../../../_shared/madame/madame-service';
const styles_App:any[] = [i0.styles];
export const RenderType_App:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_App,
    data:{}});
export function View_App_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),1,'login-modal',([] as any[]),(null as any),(null as any),(null as any),
      i2.View_LoginModal_0,i2.RenderType_LoginModal)),i1.ɵdid(4374528,(null as any),
      0,i3.LoginModal,[i1.ChangeDetectorRef],(null as any),(null as any)),(_l()(),
      i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(16777216,(null as any),(null as any),
      1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),i1.ɵdid(212992,(null as any),0,i4.RouterOutlet,[i4.ChildrenOutletContexts,
      i1.ViewContainerRef,i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],
      (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,5,0);
  },(null as any));
}
export function View_App_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_App_0,RenderType_App)),
      i1.ɵdid(245760,(null as any),0,i5.App,[i6.ConfigApp,i7.MetaService,i8.ProfileApp,
          i9.PermissionsApp,i10.MadameService,i4.Router,i4.ActivatedRoute],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AppNgFactory:i1.ComponentFactory<i5.App> = i1.ɵccf('app-component',i5.App,
    View_App_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1NwZWVkZXIvRG9jdW1lbnRzL25neC1mdWNrL3N0cmljdGRldi9wdWJsaWNfd2Vic2l0ZS9zcmMvYnJvd3Nlci9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL1NwZWVkZXIvRG9jdW1lbnRzL25neC1mdWNrL3N0cmljdGRldi9wdWJsaWNfd2Vic2l0ZS9zcmMvYnJvd3Nlci9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHAuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL1NwZWVkZXIvRG9jdW1lbnRzL25neC1mdWNrL3N0cmljdGRldi9wdWJsaWNfd2Vic2l0ZS9zcmMvYnJvd3Nlci9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgPGxvZ2luLW1vZGFsPjwvbG9naW4tbW9kYWw+XG4gIDxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD4iLCI8YXBwLWNvbXBvbmVudD48L2FwcC1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEseUNBQ0U7TUFBQTttREFBQSxVQUFBO01BQUEsb0VBQTJCO2FBQUEsMEJBQzNCO01BQUE7TUFBQSx1QkFBQTtzREFBQTtNQUFBO0lBQUE7Ozs7b0JDRkY7TUFBQTthQUFBO3lFQUFBO1VBQUE7SUFBQTs7OzsifQ==
