/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../_shared/login/browser/views/login-modal.ngfactory';
import * as i2 from '../../../../../../_shared/login/browser/views/login-modal';
import * as i3 from '@angular/router';
import * as i4 from '../../../../src/browser/app/app.component';
import * as i5 from '../../../../../../_shared/config/config.app';
import * as i6 from '@ngx-meta/core/src/meta.service';
import * as i7 from '../../../../../../_shared/config/profile.app';
import * as i8 from '../../../../../../_shared/config/permissions.app';
import * as i9 from '../../../../../../_shared/madame/madame-service';
const styles_App:any[] = ([] as any[]);
export const RenderType_App:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_App,
    data:{}});
export function View_App_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'login-modal',([] as any[]),(null as any),(null as any),(null as any),
      i1.View_LoginModal_0,i1.RenderType_LoginModal)),i0.ɵdid(4374528,(null as any),
      0,i2.LoginModal,[i0.ChangeDetectorRef],(null as any),(null as any)),(_l()(),
      i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(16777216,(null as any),(null as any),
      1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),i0.ɵdid(212992,(null as any),0,i3.RouterOutlet,[i3.ChildrenOutletContexts,
      i0.ViewContainerRef,i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
      (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,5,0);
  },(null as any));
}
export function View_App_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_App_0,RenderType_App)),
      i0.ɵdid(245760,(null as any),0,i4.App,[i5.ConfigApp,i6.MetaService,i7.ProfileApp,
          i8.PermissionsApp,i9.MadameService,i3.Router,i3.ActivatedRoute],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AppNgFactory:i0.ComponentFactory<i4.App> = i0.ɵccf('app-component',i4.App,
    View_App_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU3BlZWRlci9Eb2N1bWVudHMvbmd4LWZ1Y2svc3RyaWN0ZGV2L3B1YmxpY193ZWJzaXRlL3NyYy9icm93c2VyL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1NwZWVkZXIvRG9jdW1lbnRzL25neC1mdWNrL3N0cmljdGRldi9wdWJsaWNfd2Vic2l0ZS9zcmMvYnJvd3Nlci9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL1NwZWVkZXIvRG9jdW1lbnRzL25neC1mdWNrL3N0cmljdGRldi9wdWJsaWNfd2Vic2l0ZS9zcmMvYnJvd3Nlci9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHAuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL1NwZWVkZXIvRG9jdW1lbnRzL25neC1mdWNrL3N0cmljdGRldi9wdWJsaWNfd2Vic2l0ZS9zcmMvYnJvd3Nlci9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgPGxvZ2luLW1vZGFsPjwvbG9naW4tbW9kYWw+XG4gIDxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD4iLCI8YXBwLWNvbXBvbmVudD48L2FwcC1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQSx5Q0FDRTtNQUFBO21EQUFBLFVBQUE7TUFBQSxvRUFBMkI7YUFBQSwwQkFDM0I7TUFBQTtNQUFBLHVCQUFBO3NEQUFBO01BQUE7SUFBQTs7OztvQkNGRjtNQUFBO2FBQUE7d0VBQUE7VUFBQTtJQUFBOzs7OyJ9
